version: "3.0"
services:
  chat_server:
    container_name: chat_server
    build: ./server
    env_file:
      - env/local.server.env
    volumes:
      - ./server:/home/server
      - ./server/node_modules:/home/server/node_modules
    depends_on:
      - chat_db_mongo
    network_mode: "host"

  chat_db_mongo:
    container_name: chat_db_mongo
    image: mongo
    env_file:
      - env/local.server.env
    network_mode: "host"
